### ISSUE TITLE
automated search for multimodal distributions

### ISSUE THREAD

**Issue by AidanRocke** [openworm/behavioral_syntax#11]
In order to find discrete behaviors/biological signatures in an automated manner it might be interesting to write a program that automatically looks for multimodal distributions across all continuous features(turning angle, pauses...).

**Comment by AidanRocke** [comment]
I could use PyStan or some other MCMC library for this. Here's an introductory tutorial: https://github.com/twiecki/WhileMyMCMCGentlySamples/blob/master/content/downloads/notebooks/MCMC-sampling-for-dummies.ipynb

**Comment by MichaelCurrie** [comment]
@AidanRocke is back, baby!  Nice to see you again.  :)

**Comment by ghost** [comment]
Yes. I realised that the first time I worked on 'behavioural syntax' I was
trying to do too many things
at once. Now, I think I have a simpler solution.

Instead of producing lab reports which is definitely possible, I'll build a
web-based application that
will simply produce three possible answers given image/video input: 'Yes',
'NO' or 'Maybe'.

That's something most humans would understand. :) My hope is that it will
inspire new people to contribute
to OpenWorm.

I'll try to take small steps on it this week but next week and the coming
weekend is when I'll truly be
able to make important changes.

Aidan

**Comment by MichaelCurrie** [comment]
Sounds like an interesting approach!  Starting with something simple is usually better, I agree.
